### ISSUE TITLE
Minor issue with zsh when using help from lazy import errors

### ISSUE THREAD

**Issue by prashantgupta24** [IBM/import-tracker#57]
## Describe the bug

When using lazy import errors in `import_tracker`, if the import error is triggered within a module that is managed as an extras set, the error message is updated to include instructions on which extras set needs to be installed. The error message might look something like this:

```bash
ModuleNotFoundError: No module named 'example_module'. 
To install the missing dependencies, run `pip install my_module[my_module.example_module]`
```
If the command `pip install my_module[my_module.example_module]` is executed within a `zsh` environment, an error occurs:
```bash
zsh: no matches found: my_module[my_module.example_module]
```
since square brackets in `zsh` have special meanings. 

## Platform

Please provide details about the environment you are using, including the following:

-   Interpreter version: 3.8
-   Library version: 2.2.2

## Sample Code

When `pip install my_module[my_module.example_module]` is executed within a `zsh` environment, an error occurs:

```bash
zsh: no matches found: my_module[my_module.example_module]
```

## Expected behavior

The command should work on zsh.

**Comment by gabe-l-hart** [comment]
Closed by #56
