### ISSUE TITLE
Error when building the wheel in Python 3.11

### ISSUE THREAD

**Issue by wai25** [IBM/import-tracker#74]
## Describe the bug
When building the wheel in Travis/Python 3.11, we get the following error:
```
python3 setup.py bdist_wheel --python-tag py311 clean --all
....
Traceback (most recent call last):
  File "/app/setup.py", line 108, in <module>
    ) = import_tracker.setup_tools.parse_requirements(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/import_tracker/setup_tools.py", line 80, in parse_requirements
    library_import_mapping = track_module(
                             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/import_tracker/import_tracker.py", line 79, in track_module
    req_imports, opt_imports = _get_imports(module_to_check)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/import_tracker/import_tracker.py", line 426, in _get_imports
    op_num = _get_op_number(line)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/import_tracker/import_tracker.py", line 327, in _get_op_number
    opcode_idx = min([i for i, val in enumerate(line_parts) if val.isupper()])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence
```
## Platform

Please provide details about the environment you are using, including the following:

-   Interpreter version: Python 3.11.4
-   Library version: import_tracker 3.1.5

## Sample Code

Please include a minimal sample of the code that will (if possible) reproduce the bug in isolation
`python3 setup.py bdist_wheel --python-tag py311 clean --all`

## Expected behavior

No errors on import

## Observed behavior

What you see happening (error messages, stack traces, etc...)

## Additional context
Watson NLP build/ubi8
Tensorflow 2.14.1

No issues in py3.9, py3.10

**Comment by Fred-Fan** [comment]
I am guessing the issue is caused by `dis` has some changes in py3.11 so its return is a little different. And in some cases, it will return the list just contains lowercase or digits. So this line of code will fail due to the empty list after filtered.
```
opcode_idx = min([i for i, val in enumerate(line_parts) if val.isupper()])
```
I have a temp fix for [the function](https://github.com/IBM/import-tracker/blob/16e7322d55733b933a27888f8a2ba9a5e8cbdaba/import_tracker/import_tracker.py#L322C5-L322C19) `_get_op_number` as below and we verified it works for Watson NLP.
```
def _get_op_number(dis_line: str) -> Optional[int]:
    """Get the opcode number out of the line of `dis` output"""
    line_parts = dis_line.split()
    temp = [i for i, val in enumerate(line_parts) if val.isupper()]
    if not temp:
        return None
    opcode_idx = min(temp)
    assert opcode_idx > 0, f"Opcode found at the beginning of line! [{dis_line}]"
    return int(line_parts[opcode_idx - 1])
```
Could any maintainer have a check if there are any risks for this change? 
@gabe-l-hart @gkumbhat @joerunde

**Comment by gkumbhat** [comment]
Thanks @Fred-Fan for finding this issue. Can you please create a PR with the fix.

**Comment by Fred-Fan** [comment]
[PR](https://github.com/IBM/import-tracker/pull/75) is created

**Comment by Fred-Fan** [comment]
Close since it is solved
