### ISSUE TITLE
Figure Out Logging

### ISSUE THREAD

**Issue by alex-jw-brooks** [IBM/import-tracker#8]
## Is your feature request related to a problem? Please describe.

Some logging would be really helpful here for debugging, especially for some of the gnarly implementation details functions that are for the most part best effort and trying to look at pip installed packages.

This issue is for deciding
1. What we should use for logging and why
2. Actually adding some initial logs

## Describe the solution you'd like

Import Tracker has no external dependencies at the moment, which is awesome. It would be neat to keep it this way; let's explore `logging` first before trying anything else. Comments will follow in the issue.

## Describe alternatives you've considered

- External packages like [alog](https://pypi.org/project/alchemy-logging/)
    - Super nice and useful but also means adding actual dependencies which is not necessarily a good thing
- Print 😬

**Comment by gabe-l-hart** [comment]
Closed by #20
